### ISSUE TITLE
Add Clinical Alert component

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-clinical#162]
# Issue Description
A clinical alert component is needed that extends the terra-alert component with clinical specific alert types. Right now those would be Gap Checking and Outside Records types

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
This should work exactly the same as the base terra-alert component, just an extension of the alert types provided.

**Comment by jmsv6d** [comment]
Blocked until terra-alert base component is merged.

**Comment by emilyrohrbough** [comment]
This can be closed since the Unsatisfied (gap checking) and Unverified (outside records) alert types were added to terra-alert in https://github.com/cerner/terra-core/pull/2941 and release in [v 4.29.0 on May 12, 2020](https://github.com/cerner/terra-core/blob/master/packages/terra-alert/CHANGELOG.md#4290---may-12-2020).
