### ISSUE TITLE
Centered Header Text

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#171]
# Issue Description

Center text on the Header component instead of the current left-aligned text.
For example:
<img width="325" alt="screen shot 2017-07-31 at 4 08 59 pm" src="https://user-images.githubusercontent.com/6981195/28798839-626074c2-760b-11e7-9581-b035aca8b897.png">

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Text is centered when relevant prop is provided.

## Current Behavior

Text can only be left-aligned.

## Steps to Reproduce

N/A

## Environment

* Component Version: 1.1.1
* Browser Name and Version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): macOS 10.12.6 (16G29)

**Comment by emilyrohrbough** [comment]
Issue initially logged in terra-core https://github.com/cerner/terra-core/issues/683 by @noahbenham

**Comment by PaulSolDev** [comment]
@emilyrohrbough  So the request is to have an attribute that allows header text to be left aligned (default) or centered?

**Comment by emilyrohrbough** [comment]
@PaulSolDev yes this is the request

**Comment by PaulSolDev** [comment]
@emilyrohrbough it appears that there is already an existing requirement around this functionality.  1106959: https://jazz.cerner.com:9443/rm/resources/_39DLEIT3EeaYQbtTQDvZHA

**Comment by noahbenham** [comment]
Discussed with @emilyrohrbough. I'd like to pick this up & expect to begin working on it within the next couple of weeks. If any consumers need it sooner, please let me know and I'll re-prioritize.

**Comment by ryanthemanuel** [comment]
Hi @noahbenham, is there a UX designer you've been working with on what you're trying to accomplish?  In the new Terra world, we've locked down headers to only have left aligned text due to consistency and technical concerns.  If we want to extend that capability, I'd like to see that come from UX directly.  I'm going to close this for now, but we can reopen it if need-be.

**Comment by neilpfeiffer** [comment]
Reopening issue and having discussion needs from other UX designers. We will be gathering feedback and make a recommendation on how to proceed with this enhancement.

**Comment by noahbenham** [comment]
Thanks @neilpfeiffer. Curious if you have an estimated ETA for this decision? For our use case, here are a few UX design samples with our own custom Header component:
[Contacts Visual Design](https://wiki.ucern.com/display/public/DevMethodology/CareAware+Connect+Contacts+Visual+Design) | [Messaging Visual Design](https://wiki.ucern.com/display/public/DevMethodology/CareAware+Connect+Messaging+Visual+Design) | [Alerting Visual Design](https://wiki.ucern.com/display/public/DevMethodology/CareAware+Connect+Alerting+Visual+Design)

If this enhancement doesn't proceed, our headers would (obviously) become left centered per your recommendation.

**Comment by neilpfeiffer** [comment]
Going to close for now and regroup with UX designers as reason for Engineering complexity due to variable content areas on the left and right sides. FWIW - left alignment also currently aligns with MPage patterns for component headers. 

We may solve with additional/variant components in the future and will gather input from UX as to what those components might be to solve this request.
