### ISSUE TITLE
Height constraints on site demo

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-clinical#176]
# Issue Description

The height of the container for the demo portion of the site is causing the content to collapse.
![screen shot 2017-08-08 at 8 27 35 am](https://user-images.githubusercontent.com/6720991/29074062-8eaa54fe-7c13-11e7-9b89-7cd853a48ce1.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

The Demo height should occupy the height of the window.

## Current Behavior

The content is collapses. 

## Steps to Reproduce

1. Navigate to http://engineering.cerner.com/terra-clinical/#/demo

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by emilyrohrbough** [comment]
I looked into this. The reason you saw the issue initially was due to the conversion to css modules with the ModalManager. For whatever reason, the modal manger's container was not style-bound at the time this issue was logged. The latest deployed version of http://engineering.cerner.com/terra-clinical/#/demo does however have the most recent changes and the application demo appears as expected.
