### ISSUE TITLE
Make header compatible with the collapsible menu view

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-clinical#192]
# Issue Description
The collapsible menu view is going need to be used in headers, the collapsible menu view will take up all space available to it so the header will need the content sections to have a constrained width to keep the collapsible menu view from taking up the entire header. 

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The header should have a max width set on the content sections.

## Current Behavior
The content sections of the header can take up as much space as they want causing the content to expand the entire width of the header.

**Comment by cwalten** [comment]
We are experiencing an issue related to this.

## Expected Behavior
When a collapsible menu is added as a child to an action header, and onBack and onClose methods are provided, all buttons should be visible in the header.

## Current Behavior
The collapsible menu pushes the Close button off of the screen, forcing it to wrap. (see attached screenshot)

<img width="560" alt="screen shot 2017-11-07 at 4 16 58 pm" src="https://user-images.githubusercontent.com/19825717/32521009-938b2802-c3d7-11e7-8727-b3a4ccb87a66.png">

**Comment by kschuste** [comment]
@cwalten I believe this occurs as the div (action_header) containing your contents needs to have it's width be 100% and have a display of 'flex'.  This should allow the button to layout next to each other.
<img width="1007" alt="screen shot 2017-11-08 at 1 50 37 pm" src="https://user-images.githubusercontent.com/1711642/32571136-fd7516ba-c48b-11e7-950c-dcd9dc684cb3.png">

**Comment by tm4027** [comment]
JIRA created

**Comment by mjhenkes** [comment]
resolved with #225
