### ISSUE TITLE
rtl truncation in Header component

### ISSUE THREAD

**Issue by mikertr** [cerner/terra-clinical#197]
# Issue Description
truncation is occurring on the wrong side of the string when Header is in rtl mode.

![screen shot 2017-09-26 at 4 31 30 pm](https://user-images.githubusercontent.com/10879130/30885438-ea565a32-a2d8-11e7-83f8-e99b815d2480.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Ellipsis should display at the end of the string.

## Current Behavior
Ellipsis displays at the before the string.  String simply cuts off where it runs out of real estate.

**Comment by emilyrohrbough** [comment]
@mikertr which browser did you see this in?

**Comment by mikertr** [comment]
@emilyrohrbough macOS Safari 10.1.2.  I see it's behaving differently in Chrome (truncating the beginning of the string).  Are we sure that either one of these scenarios is ideal?  There's value in the ability to front-truncate, but I don't think you'd want to assume that you want to truncate the beginning of a string just because you were in rtl mode.

**Comment by bjankord** [comment]
The above issue is due to using strings of text in language and in a directionality which they would not normally be displayed in, not necessarily an issue with the UI component.

English content should not be displayed in RTL. Languages that are read in RTL, like Arabic, should be the only languages we display in RTL. For the doc / test site, we don't swap out the language characters as one should when flipping directionality so we have this issue where we have English content in RTL mode which renders truncation oddly.

If the component used Arabic content when it was in RTL, the truncation on the right hand side would be correct.

**Comment by mikertr** [comment]
@bjankord Thank you for providing some context.  I still believe the screen shot I included above may be an issue in Safari.  At the very least, the behavior is inconsistent in Safari vs. Chrome.

**Comment by neilpfeiffer** [comment]
Need to validate that this is resolved by PR #203 [closed] which switches header text truncating and now wraps instead.
