### ISSUE TITLE
Update ItemDisplay to use em's instead of px for Inline Icon minimum.

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-clinical#244]
# Issue Description
Update the minimum size child selector for inline-icons in the item display to use an em/rem for min-height and min-width, to ensure if the font size of the item display is changed it will sync with the text in the item display.

Also will resolve #259

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
 We should be using em's in the case we set the themeable font-size value so when the 760px break point has the icon scale with the text font. We should use em/rems.

## Current Behavior
Currently icons are set to a px value.

**Comment by dkasper-was-taken** [comment]
1em would seem appropriate, but we should make sure to check with UX.

**Comment by neilpfeiffer** [comment]
Three updates to make:
1. Lets set the minimum icon size to  `min-height: 1em;`  `min-width: 1em;` 

https://github.com/cerner/terra-clinical/blob/c13cdf1ec555c7aa26dce58f55a936db72b1f062/packages/terra-clinical-item-display/src/ItemDisplay.scss#L23-L26

2. change the icon  `padding-right: 5px;` to `padding-right: 0.3571428571rem;`

https://github.com/cerner/terra-clinical/blob/c13cdf1ec555c7aa26dce58f55a936db72b1f062/packages/terra-clinical-item-display/src/ItemDisplay.scss#L20

3. It also has been reported the responsive resizing is unexpected and causing issues (since everywhere else in Terra we have removed responsive text sizing for below the small breakpoint). I think this was a holdout from older Orion code - lets remove the media query entirely and set the `.terra-clicinal-item-body` to `font-size:1rem` only.

https://github.com/cerner/terra-clinical/blob/c13cdf1ec555c7aa26dce58f55a936db72b1f062/packages/terra-clinical-item-display/src/_mixins.scss#L9-L16
