### ISSUE TITLE
ItemCollection loses selection when consumed with SlidePanelManager (with squish panelBehavior)

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-clinical#386]
# Bug Report

## Description

When ItemCollection is used with SlidePanelManger and we select an Item from ItemCollection, the Item is not selected anymore. 
## Steps to Reproduce

1. use [ItemCollection](https://engineering.cerner.com/terra-clinical/#/components/terra-clinical-item-collection/clinical-item-collection) with [SlidePanelManager with squish panelBehavior](https://engineering.cerner.com/terra-framework/#/components/terra-slide-panel-manager/slide-panel-manager/slide-panel-manager).
2. Select an item in ItemCollection, when the panel opens, the Item in not selected in ItemCollection (see screenshot). This happens only on the first selection. 
When you select another Item or the same Item now, it will be selected. (see second screenshot) 

## Additional Context / Screenshots
First selection
<img width="1024" alt="screen shot 2018-08-09 at 12 08 50 pm" src="https://user-images.githubusercontent.com/16544484/43914324-394998c8-9bcd-11e8-8efd-05f8b2a5f503.png">
Second selection
<img width="1028" alt="screen shot 2018-08-09 at 12 14 13 pm" src="https://user-images.githubusercontent.com/16544484/43914604-ee474266-9bcd-11e8-9460-24e76e699738.png">

## Expected Behavior

On initial selection, the listItem should be selected.

## Environment

* Component Name and Version: ItemCollection (3.14.0)
* Browser Name and Version: All
* Node/npm Version: Node 8.9.2/npm 5.6
* Webpack Version: 4.16.5
* Operating System and version (desktop or mobile):

**Comment by tbiethman** [comment]
@mayurikini This issue is due to the ItemCollection's transition from a Table to a List when the SlidePanel is opened. In your `onSelect()` implementation, you will need to re-render the ItemCollection with the proper ItemCollection.Item's`isSelected` prop set. That will ensure the item remains selected as the ItemCollection transitions between its two implementations.

I don't believe you are setting the `isSelected` prop at all today. Your second image is showing the 'focus' style for the list item, not the 'selected' style. You can see how the List selections should look in the example here: https://engineering.cerner.com/terra-core/#/components/terra-list/list/selectable-list

I'm going to close this issue, but please reach out if you have more questions regarding your implementation.
