### ISSUE TITLE
Violation in Onset Picker not resolving as expected

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-clinical#397]
# Bug Report

## Description

(Firefox only) When manually updating a value in the onset picker that causes a violation (exceeding the rules of 2 for Week >8 and Month >24) the corresponding field shows a violation.  Changing the unit value does not clear the violation.

Oddities- changing from units from weeks to months clears the violation as expected but changing from weeks to years or months to years does not.

## Steps to Reproduce

1. (in Firefox) Choose 'Age' in the Onset Picker
2. Select a unit of 'weeks'
3. Manually enter a value >8 and select an area outside of the field (violation appears)
4. Change the unit to years (note that the violation does not clear)
5. Select the value field and attempt to use the toggle up option (value does not change)
6. Select the toggle down option (unit drops to a significantly lower value and clears violation)
7. With a unit of years still selected change the value to >24 (notice that a violation occurs despite this being an accepted value for a unit of years)

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/29487301/45774300-3803b380-bc12-11e8-9cd3-9a5f3f93e3f0.png)

![image](https://user-images.githubusercontent.com/29487301/45774282-30440f00-bc12-11e8-8b57-9320bff5334b.png)

## Expected Behavior

Follow rule of 2 and clear violations based on current field settings.

## Environment

* Component Name and Version: Onset Picker
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Desktop

**Comment by ryanthemanuel** [comment]
@doogthemushroom is going to pick this up.

**Comment by doogthemushroom** [comment]
> 1. (in Firefox) Choose 'Age' in the Onset Picker
> 2. Select a unit of 'weeks'
> 3. Manually enter a value >8 and select an area outside of the field (violation appears)

So this seems correct so far following rule of 2. This 'violation' is also happening on other browsers but none have this styling. If you followed these steps to reproduce on the handled picker example and clicked 'Submit' in between the steps, you'd see a popup occur in chrome at the very least.

> 4. Change the unit to years (note that the violation does not clear)

It's causing a violation here because the # of years puts the onset date in the future. In this case, the birthdate was 6 years ago and you are trying to set the date 8 years from the birthdate, that's a violation. No future dates.

> 5. Select the value field and attempt to use the toggle up option (value does not change)

Expected, as you shouldn't be able to enter a date in the future.

> 6. Select the toggle down option (unit drops to a significantly lower value and clears violation)

Expected, as it's dropping to the maximum allowed value.

> 7. With a unit of years still selected change the value to >24 (notice that a violation occurs despite this being an accepted value for a unit of years)

Relates back to what I said for step 4. If the birthdate was 6 years ago, any value above 6 will cause a violation.


So seems like it's not clear that the age value restrictions are in place because it would end up calculating a future date. I can see how the age values not increasing, and decreasing to the maximum value could be a little wonky for the user.

**Comment by jmsv6d** [comment]
As per @doogthemushroom 's comment, it looks like the component itself is behaving as expected, but there might be inadequate documentation on how the birthdate limits the onset date to be no earlier than the birth day. This is documented on the props table for the birthdate prop but the site examples should likely be updated to show what birthdate is set to for each example, this is already done on the test pages.
