### ISSUE TITLE
[terra-clinical-item-view] Wrapping right aligned displays are no longer right aligned when they are wrapped

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-clinical#463]
# Bug Report

## Description

Wrapping right aligned displays are no longer right aligned when they are wrapped.

This could potentially be fixed with a text-align of end within the 2 column layout on the even item (https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-view/src/ItemView.scss#L90-L97).

**Comment by ShettyAkarsh** [comment]
Here setting **text-align: end** will fix this issue when there is only **text** used within the column . But along with **icon**  and the **text** in the same column , there is some amount of space being created between the icon and text  due to **text-align: end**  and when there is wrapped words that have equal amount of space between each then there is a chance of  extra space being added at the left from the beginning of div till its content. as the property  **word-break: break-word** is set. the words are broken upon at the spaces in between during multiline wrapping.

Below are the screenshots

After the change only with the text.

![image](https://user-images.githubusercontent.com/45097016/54226840-a6239600-4524-11e9-9053-b545b8cdd8b7.png)

Icon and text together.

![image](https://user-images.githubusercontent.com/45097016/54226980-f0a51280-4524-11e9-8079-f557582a28cf.png)

So my question here is for icon along with the text. do we need to fix the space issue that is being created between after this change ?  or will that be fine to display like this ?

@ryanthemanuel , @neilpfeiffer  Please share your thoughts on this.

**Comment by neilpfeiffer** [comment]
Funny - technically the component is performing as intended since it isn't the inner text of the `terra-clinical-item-display` that is right aligned, but the `ItemView.Display` wrapper around whatever element is provided that aligns itself to the right. 


I think we should do two things, first for Item Display and the second for Item View:

1. Rework the css for terra-clinical-item-display,  the current flex rules is causing it to fill the space more than it needs to, so when text is right aligned, there is a more pronounced gap between text and icon.  Also, enhance `terra-clinical-item-display` to add a new prop `iconAlignment` with values of `center`, `top`, and `inline`, which would change how the icon gets positioned within the item display when it wraps, similar to these layouts:

<img width="707" alt="Screen Shot 2019-03-14 at 9 44 00 AM" src="https://user-images.githubusercontent.com/1355485/54365933-c4c98000-463d-11e9-9340-7e681f03436c.png">

2. Then as you suggest - in `Item View`, in the `.content:nth-child(even)` adding `text-align: end;` will cascade and cause the inner text to align right. To look correct if the display also had an icon, the consumer would just need to add the `iconAlignment=inline` or `top` to more correctly position the icon with the wrapping right aligned text.  

https://github.com/cerner/terra-clinical/blob/c64de5eec14c511955685a494d6469e04d0555e8/packages/terra-clinical-item-view/src/ItemView.scss#L90

**Comment by ShettyAkarsh** [comment]
Thanks @neilpfeiffer, 

I tried your suggestion of Setting the **display** property of Terra-Clinical-item-display div to **inline-flex** and its **inner text** div  as **inline-block**. it still display the same. still the space exists between the icon and the wrapped  text. myself even tried various other combination of display value for  item-display ,inner-text and inner-icon but still the issue exists.

During my further investigation of item-display i observed, when there is a single line sentence the inner-text div width is equal to content width. 

![image](https://user-images.githubusercontent.com/45097016/54601726-c643df80-4a65-11e9-86e6-128190364876.png)

When the sentence exceeds further the div width also gets increased as the max-width of item-display is set to 100%.  during this if it is found that upcoming words will not be able to fit in the same line. then these words get wrapped in the next line but still the extra space added at the right does not gets removed.

![image](https://user-images.githubusercontent.com/45097016/54602109-bd074280-4a66-11e9-83be-f2a209538748.png)

so hence during text-align set to end this text aligns to right by adding the same space that was in the end to the start of the div.

![image](https://user-images.githubusercontent.com/45097016/54602336-6d754680-4a67-11e9-9166-566dddcad45e.png)

This issue is there for all type of display property value. (block, inline-block, flex, inline-flex etc..)

Also this is behaving correctly as this mainly depends on the text content what we provide to the div. if i modify the existing div text sentence by adding extra word let say 'display' in between then there is no issue. 

![image](https://user-images.githubusercontent.com/45097016/54602640-3ce1dc80-4a68-11e9-948f-2b6e4f2f3a8d.png)
 
This is because when the words are getting written into the div then the width of the div also gets increased to the parent width. once the parent width is reached and the next upcoming words could not fit into same line then the line break occurs. if the next word fits in the same line then it is printed first and then the new line break occurs. hence this space issue majorly depends on the text sentence what we provide to the inner text div of the terra-clinical-item-display.

so to be on the safer side for the whatever possibilities of the text-sentence provided. my thought is to better have the icon alignment inline with the text sentence. which will fix this space issue in between the icon and text wrapped.

![image](https://user-images.githubusercontent.com/45097016/54603346-158c0f00-4a6a-11e9-9cf7-1d0c8c193aa2.png)

In item view this displays as below.

![image](https://user-images.githubusercontent.com/45097016/54603687-f8a40b80-4a6a-11e9-9a54-997ba2b56716.png)

Please let me know your thoughts on this.
