### ISSUE TITLE
Sticky headers for sections in the Terra Clinical Data Grid

### ISSUE THREAD

**Issue by faizahmedshaik** [cerner/terra-clinical#480]
# Feature Request

## Description

The Sub-section headers on the clinical data grid scroll off as the user scrolls through the data grid.  For a large section, this will result in losing context of the section or immediate access to any buttons on the header for the section.  It would be good to have the header stick to the top as the user scrolls.

## @ Mentions

Spoke with @tbiethman about this briefly.

**Comment by JakeLaCombe** [comment]
Having this functionality inside requires use of the CSS4 attribute position: sticky. (https://developer.mozilla.org/en-US/docs/Web/CSS/position). The minimum support for this browser is Edge, which is higher than or minimum support browser of IE10. Since we do not have a good way of having a cross browser solution for this feature, we can not support this presently. Once we have dropped support for IE, we can revisit this feature request.
