### ISSUE TITLE
[clinical-detail-view] IE wrapping issue for label-value-views

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-clinical#516]
# Bug Report
Wrapping issue with `clinical-label-value-view` inside of `detail-view-list` on IE

## Steps to Reproduce
1. Have long content in a detail-view-list item (label-value-view)
2. View on IE.

## Additional Context / Screenshots
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1355485/59137259-8695e100-894c-11e9-8092-a63d3fa1508c.png)

## Expected Behavior
`clinical-label-value-view` in `detail-view-list` should wrap, need to check css to make sure correct styles are being applied. Most likely similar issue with flex bug noted [here](https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11).

## Environment
* IE 10/11

**Comment by dkasper-was-taken** [comment]
As noted offline: Setting 100% max-width on the DetailList.Item alleviates the issue well enough.

**Comment by avinashg1994** [comment]
On further analysis I found the following:
1. The issue is **not reproducible** in IE11, as seen in the screenshot
<img width="960" alt="IE11" src="https://user-images.githubusercontent.com/50138162/59264509-ddf3c400-8c60-11e9-900d-d9b3acd9f11e.png">
2. The issue is **reproducible** is IE10, as seen in the screenshot
<img width="960" alt="IE10" src="https://user-images.githubusercontent.com/50138162/59264655-36c35c80-8c61-11e9-9246-ee7e461dba59.png">
3. Even though we do not support Terra for IE9, but for the purpose of verifying whether it is an browser issue or not i checked it in IE9 as well and it is **not reproducible**, as seen in the screenshot
<img width="960" alt="IE9" src="https://user-images.githubusercontent.com/50138162/59264768-7722da80-8c61-11e9-880f-ff1cb12f20ec.png">

Since the issue is not reproducible in IE11 and IE9 and only persists in IE10, I suspect that this is an **browser issue**.
I also tried to to set the max-width to 100% as suggested, but the issue is still not reproducible in IE11.
@neilpfeiffer, your thoughts on this.
