### ISSUE TITLE
[clinical-onset-date-picker] Onset Picker Doesn't Calculate Age Correctly When Given Leap Day Birthdate

### ISSUE THREAD

**Issue by austenator** [cerner/terra-clinical#593]
# Bug Report

## Description

When a leap day birthdate is given to the onset picker (e.g. '2000-02-29' which is a leap day) when changing granularities it miscalculates the age.

## Steps to Reproduce

1. Give the onset picker a leap day birthdate (e.g. '2000-02-29')
2. Switch granularity to year and enter 2003 (a non-leap-year)
3. Switch granularity to age and witness that the correct age of 3 is not shown but 2.

## Expected Behavior

I expect the onset picker to correctly calculate leap-day birthdate ages.

## Possible Solution

If given a leap day birthdate, it should fall forward a day and default to 'YYYY-03-01' or March 01 YYYY to calculate the age field.

## Environment

* Component Name and Version: "terra-clinical-onset-picker": "4.10.0"
* Browser Name and Version: Chrome Version 78.0.3904.108
* Node/npm Version: [e.g. Node 8/npm 5] v8.9.2/5.5.1
* Webpack Version: 4.41.2
* Operating System and version (desktop or mobile): macOS Mojave 10.14.6

**Comment by gabeparra01** [comment]
My team is also using clinical-onset-date-picker. We are releasing to testing partners in Q1 and clients in Q2. This could be reported as a CHIA

**Comment by graceschreur** [comment]
The Onset Picker is used in One Plan's Health Concerns Orion component.  This impacts our team as well.

**Comment by nramamurth** [comment]
I did some initial investigation and here's what I see —

**Case 1:**

precision: Before
birthDate: 2000-02-29 (29th Feb, 2000)
onSetDate (initial): 2013-02-13 (13th Feb, 2013)

In this, when you select the "Year" granularity as "2003", then the onSetDate is now "2003-02-13", which means **age is 2 Years 11 Months X days**. This means that the "Age" granularity shows "2 Years". Why do you think it should read "3 Years" when the actual age is not 3 *yet*? 

Although I think this is correct behaviour, I see something else that could potentially be an issue: when you would like to change the granularity back to Years now, you'd notice that "2003" is now changed to "2002" - which I think is a problem. 

I might be wrong here, but I'd like to to hear from @ryanthemanuel / @benbcai / @neilpfeiffer / @PaulSolDev about the correct behaviour. 

1. What should "Age" granularity read when the calculated onSetDate is between 2000-02-29 and 2003-02-13? Should it be 2 or 3? 

2. What should "Years" granularity read when the calculated onSetDate is between 2000-02-29 and 2003-02-13? Should it be 2003 or 2002? 

**Case 2:**

precision: Before
birthDate: 2000-02-29 (29th Feb, 2000)
onSetDate (initial): 2013-03-02 (2nd Mar, 2013)

In this case, when you select the "Year" granularity as "2003", then the onSetDate is now "2003-03-02", which means that the **age is 3 Years X days**. This  implies that the "Age" granularity will show "3 Years", which is expected, imo.

--- 

The same behaviour that you have explained can actually be seen with non-leap year birth dates as well. Here's how - 

precision: Before
birthDate: 2001-01-25 (25th Jan, 2001)
onSetDate (initial): 2013-02-13 (13th Feb, 2013)

Choose "Date" as the granularity and choose maybe "2012-01-05". Now the actual age is **10 Years 11 Months X Days**, so the Age granularity changes to "10" because it is technically not 11 yet. When you now check the "Years" granularity, it'd show 2011 and not 2012 (which should be fixed (?)).

**Comment by saket2403** [comment]
cc @doogthemushroom

**Comment by austenator** [comment]
Thank you for the detailed investigation and response- 

I went back and it was indeed on the second 'Age' granularity select we were seeing this, which is the problem you already laid out with year, but also with age. 

The steps I just used:

InitialDate: empty
Birthdate: 2000-02-29

1. Select date granularity and choose a date after the birthdate (I chose today, 2019-12-06).
2. Switch granularity to Year. It shows 2019.
3. Change year to 2003.
4. Switch granularity to Age. Age shows 2 (when it should be 3). If not seeing this, switch to Year and back to Age one more time.
5. Switch to Year granularity and it shows 2002 which is also incorrect. (The issue you stated above).
5. Switch to age and it now is 23 months. 
6. If saved the date is saved as 01/29/2002.

This is behavior on our picker which has some on change logic, but it seems that there is some similar behavior on your end as well.

**Comment by nramamurth** [comment]
@PaulSolDev May I know what behaviour the requirements call out?

**Comment by PaulSolDev** [comment]
Moving forward, this is an outline of the behavior I would expect when using the Onset Picker:

- When the granularity is changes the system shall clear any existing date values
- When an incomplete date value is entered the system populates the missing data to the smallest logical value (example 1: granularity=month, entered value is December 2012, the value submitted would be 12/1/2012) (example 2: granularity=year, entered value is 2012, the value submitted would be 1/1/2012)
-Granularity=Age defaults the month and day values to the corresponding birthdate (example: birthdate 4/25/1980, age value is 10, the value submitted would be 4/25/1990)
-Leap year logic: Only valid dates may be submitted.  If a calculated value returns an invalid date the system defaults forward to the next logical date (example: birthdate 2/29/2000, age value is 3, the submitted value would be 3/1/2003)

**Comment by benbcai** [comment]
It looks like this is where it updates the [onsetDate state](https://github.com/cerner/terra-clinical/blob/286ebe24d89b7ecad59a3bffa571a5f1187a17f1/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L151), which will be used to calculate the age value. The calculation basically converts the birthdate (i.e. 2000-02-29) to a moment object and adds the age value (i.e. 3) and age unit (i.e. YEAR) to it. The calculated date would end up to be 2003-02-**28**. This calculated date is will be used to then calcuate the [new age value](https://github.com/cerner/terra-clinical/blob/286ebe24d89b7ecad59a3bffa571a5f1187a17f1/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L145). Since 2000-02-29 and 2003-02-**28 is 35 months apart, instead of 36 using this [logic](https://github.com/cerner/terra-clinical/blob/286ebe24d89b7ecad59a3bffa571a5f1187a17f1/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L121), this would be considered 2 years. This [discussion](https://github.com/moment/moment/pull/571) has more details about moment calculating months in a leap year.

I couldn't find a moment API that determine if a date is a leap day. One possible solution could be to use `isLeapYear` to check if the birth year is a leap year and check for a month of February and a day of 29. If so, then add 1 day to the date [here](https://github.com/cerner/terra-clinical/blob/286ebe24d89b7ecad59a3bffa571a5f1187a17f1/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L151) before adding the age and age unit to account for a leap birthday.

**Comment by nramamurth** [comment]
@benbcai 

>  One possible solution could be to use isLeapYear to check if the birth year is a leap year and check for a month of February and a day of 29. If so, then add 1 day to the date here before adding the age and age unit to account for a leap birthday.

It is not just the leap year date that is the issue here, it's the same behaviour that I see for a non-leap year date in the scenario explained here ⬇️

https://github.com/cerner/terra-clinical/issues/593#issuecomment-562481453

I will need to further investigate whether the current implementation matches @PaulSolDev's requirements and make tweaks wherever necessary.

**Comment by PaulSolDev** [comment]
**One update:**
The onset picker should be able to default to a specific value if one is returned (for example: a modify scenario where an onset date was previously selected).  If the granularity is changed the defaulted value would no longer be expected to show.

**Comment by nramamurth** [comment]
@PaulSolDev Thanks! I'll have these changes made and have a temporary deployment done. Would you be able to take a quick look at it and let me know if the changes meet the new requirements?

**Comment by nramamurth** [comment]
@PaulSolDev @benbcai 

Here are the changes that I have made so far - 

1. When the granularity is changed, the existing data is cleared out. 
2. If granularity and onsetDate is passed to onset picker by default, then granularity fields will be **initially** populated and used until the granularity is changed. 
3. If granularity and/or onsetDate is NOT passed to onset picker by default, then no data will be **initially** populated.
4.
| Leap Year Birth Date | Granularity  | Precision | Calculated Date | Onset Date 
| ------------- | ------------- |  ------------- |  ------------- | ------------- | 
| Yes | Age | Years | Invalid | 03/01/YYYY |
| Yes | Age | Years | Valid | 02/29/YYYY |
| No | Age | Years | Valid | MM/DD/YYYY (takes MM/DD from birth date)|
| **N/A** | Month  | **N/A** | **N/A** | MM/01/YYYY
| **N/A** | Year  | **N/A** | **N/A** | 01/01/YYYY |

Draft PR: https://github.com/cerner/terra-clinical/pull/597
Deployment Pages: WIP

**Comment by PaulSolDev** [comment]
Based on the logic below I would expect the age granularity to always default the month and day to the patient's birthdate.

_Granularity=Age defaults the month and day values to the corresponding birthdate (example: birthdate 4/25/1980, age value is 10, the value submitted would be 4/25/1990)_


![image](https://user-images.githubusercontent.com/29487301/70813104-8c063500-1d8e-11ea-94fc-ab1d63d06537.png)


The logic that I added is my last comment (below) should always default the onset picker to the date granularity display so the month and day are never ambiguous.  

_The onset picker should be able to default to a specific value if one is returned (for example: a modify scenario where an onset date was previously selected). If the granularity is changed the defaulted value would no longer be expected to show._

**Comment by austenator** [comment]
Thank you all for looking into this- 

One other concern we have is that when the precision is On/At, and granularity is changed to Age, the default options are shown:
![image](https://user-images.githubusercontent.com/21992376/71182515-d4fd3400-223b-11ea-96ed-00f9f2039004.png)
Now, if our user enters a valid age number, without selecting an age precision...
![image](https://user-images.githubusercontent.com/21992376/71182814-6d93b400-223c-11ea-8689-4c8bdb89216f.png)
...our form will save and nothing will complain so our age won't be saved since a granularity was not selected (user could have meant weeks, months, years but we don't know).

Is there a way to default the age precision based on how far after the birthdate the current date is (when there is no initial onset date, e.g a fresh form)?

[Here is more detail into the desired functionality.](https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1576703422631?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1576697231951&teamName=Terra&channelName=Component%20Support&createdTime=1576703422631)

**Comment by PaulSolDev** [comment]
@austenator I agree that a form should not be able to submit an incomplete value for an onset date (missing age precision) but I'm opposed to the terra component owning any logic regarding assumptions on how a value should default.  We talked about this in scrum briefly this morning and @jmsv6d had an idea of how the former could be accomplished and will add those notes shortly.

**Comment by nramamurth** [comment]
Update: 

This issue is currently on hold and will get back to this after discussing the design and implications with @PaulSolDev, @benbcai, @neilpfeiffer and @ShettyAkarsh. 

cc / @ryanthemanuel

**Comment by PaulSolDev** [comment]
**Requirement update:**
If granularity and onset do not meet expected logic then the granularity should instead default to 'date' and the onset date is shown (see scenario 2 below). 
Note: any supplied precision value is maintained.

**Expected logic:**
- Granularity: year --then month and day should always be January 1st
- Granularity: month --then the day should always be the 1st of the month
- Granularity: age, Age unit: years --then the month and day should always match the supplied birthdate month and day (*exception only when a leap year birthdate scenario exists. In the case with a leap year birthdate to a non leap year onset the day would advance to March 1st )
- Granularity: age, Age unit: months --then the day should always match the supplied birthdate day (**exception when the birthdate day of month is greater than the available number of days in the onset month.  Example: birthday October 31st -- for months with <31 days the system should calculate the onset to the 1st day of the next month)
- Granularity: age, Age unit: weeks --then the day should always match the calculated number of days forward from the birthdate




**scenario 1: Matching scenario**
Code provided:
- Birthday provided (example: January 18, 2001)
- Precision: on/at, granularity: year, onset date: 2015-01-01

User sees:
![image](https://user-images.githubusercontent.com/29487301/71996928-b074f600-3202-11ea-8997-d8d4d3da3c9f.png)

**Scenario 2: mismatch scenario**
Code provided:
- Birthday provided (example: January 18, 2001)
- Precision: on/at, granularity: year, onset date: 2015-03-12

User sees:
![image](https://user-images.githubusercontent.com/29487301/71997075-edd98380-3202-11ea-961a-a052f74028a0.png)

**Comment by saket2403** [comment]
PR #597 has been updated with the new requirements. Please have a look at the [deployment](https://terra-clinical-deployed-pr-597.herokuapp.com/home) 
cc @PaulSolDev @neilpfeiffer .

**Comment by PaulSolDev** [comment]
Example: age< 1 week throws error when a month is selected in the following scenario:
![image](https://user-images.githubusercontent.com/29487301/72834262-09567c80-3c4e-11ea-8857-dbbc371cbea8.png)

**Comment by PaulSolDev** [comment]
**One other note:** for the tests the label for the onset picker should be "Date of Birth" as this isn't a realistic scenario.  Date of birth is required to use the onset picker and it would be more appropriate to use something like, "date of onset".
