### ISSUE TITLE
[terra-clinical-result] Multiple Value Indicator color not displaying

### ISSUE THREAD

**Issue by shinepd** [cerner/terra-clinical#620]
# Bug Report

## Description
After the [interpretationPropTypes](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/proptypes/interpretationPropTypes.js) were updated to be lower cased, the multiple value indicator is no longer showing color when a face-down value is critical.

## Steps to Reproduce
1. Create a Flowsheet Result Cell with multiple values.
2. Ensure at least one of the face-down values is critical.

## Additional Context / Screenshots

![numeric_alignment](https://user-images.githubusercontent.com/61854307/76434183-579d1780-6383-11ea-94e4-709e30d33f38.png)

## Expected Behavior
For values that are critical, the color of the multiple value indicator should change.

## Possible Solution
If the interpretation prop is to be treated as an enumerable value, I think values should be all upper cased or at least not be strict on lower casing.

## Environment

* Component Name and Version: terra-clinical-result@1.0.0
* Browser Name and Version: Chrome 80 / IE 11
* Node/npm Version: Node 8 / npm 6.13.4
* Webpack Version: ^4.41.5
* Operating System and version (desktop or mobile): desktop

**Comment by BenBoersma** [comment]
This seems to be caused by the interpretation prop being given an invalid value. As such closing the issue as not an issue.

**Comment by shinepd** [comment]
It's actually due to terra strictly enforcing the wrong casing for enumerable values, forcing consumers to write a translator function.

**Comment by mjhenkes** [comment]
@shinepd, What reference are you using to cite the correct casing of javascript enums? All terra enums are lowercase throughout our api, we are remaining consistent with ourselves.

**Comment by StephenEsser** [comment]
@shinepd 

What is the right casing for these values? Terra component Proptypes have always been case sensitive and are usually always lowercase.

**Comment by PolymorphedSquirrel** [comment]
Take a peek at this where the normalcy is provided after going to lowercase.  An interpretation of 'normal' is supplied to the FlowsheetResultCell for a normal result.

![image](https://user-images.githubusercontent.com/43280824/76792523-3aa48200-6791-11ea-8e1d-9edf88d97315.png)

When the result is not unverified and is supplied with the lowercase value, the resulting display is not retaining the space an icon would take up if present.

The screenshot in the original post is IE10 mode, with an interpretation of 'NORMAL' supplied. This should clarify that 'normal' vs 'NORMAL' and browser is not the root cause here.

**Comment by mjhenkes** [comment]
@PolymorphedSquirrel I think you are referencing this issue? https://github.com/cerner/terra-clinical/issues/617

**Comment by PolymorphedSquirrel** [comment]
@mjhenkes you are correct, I had the wrong context in my head and have updated this to be more relevant to this discussion.  Personally, I have nothing against lowercasing the value, its of no real consequence to me as a consumer, but I would expect two places using the same field provided to exhibit the same behavior.

**Comment by shinepd** [comment]
Wrong was a poor choice of words. I think when the snapshot was still out, the values were case-insensitive which aligned with our Java API and [Java Enum Best Practices](https://www.javaguides.net/2018/09/java-enums-and-annotations-best.html). Writing a case-converter isn't the end of the world, but it's also not great.

**Comment by mjhenkes** [comment]
@shinepd I wouldn't write a case converter, I'd translate keys. The fact that this component aligned with the keys being returned from your service is more by coincidence than by design. This component is intended to show results and shouldn't be tied to any particular service implementation (cerner, fhir, whatever).
