### ISSUE TITLE
View Results message flashing in a cell causes application to become unresponsive.

### ISSUE THREAD

**Issue by JananiGunasekaran** [cerner/terra-clinical#738]
# Bug Report

## Description

View Results message starts flashing in a cell when there is a checkbox present on the cell alongside a value. The View Results message width overflows past the cell width.

## Steps to Reproduce

1. Identify/create a cell with a checkbox and a numeric result that overflows the cell. 
2. This will display "View Results" message on the cell next to the checkbox. (Can also be reproduced when we resize the browser window size which will in turn reduce the size of the cell ) 
3. The "View Results" message starts flashing in the cell.
4. On inspecting the cell using dev tools, we can see that the View Results message width overflows past the cell width.

## Additional Context / Screenshots

**Flowsheet result cell with a value:**

![image](https://user-images.githubusercontent.com/60426528/105179826-cd4f4380-5b4f-11eb-922c-c70577d8ce48.png)

**Flowsheet result cell with "View Results" message:**

![image](https://user-images.githubusercontent.com/60426528/105179842-d5a77e80-5b4f-11eb-8b5a-bd35122b238e.png)

## Expected Behavior

The View Results message should display in the cell without flashing.

## Possible Solution

We can restrict this overflow of View Results message by adding style - Overflow: hidden to the flowsheet-result-cell component in terra-clinical-results. This property was earlier present in terra-clinical-results but was removed in this [PR](https://github.com/cerner/terra-clinical/pull/633/files#diff-a1ddcf8aab83b32b77a0d70d2a89972efb06e0bbe548f6cfd442b86ed5e8dc06L9). This change is necessary for us to fix the issue.

## Environment

* Component Name and Version: terra-clinical-result, v1.3.0
* Browser Name and Version: Chrome V87.0.4280.141
* Node/npm Version: Node 10/npm 6
* Operating System and version (desktop or mobile): MacOS, v10.14.6

**Comment by neilpfeiffer** [comment]
It is hard to fully understand the condition you are describing only by seeing screenshots (what is affect, what is not, what is overflowed/not-showing, etc). @JananiGunasekaran, can you do a series of additional items to provide more information:

1. Can you add a video showing the issue of the "flashing" occurring - how it starts before the situation, and then show the situation being triggered by resize (Is there any other situations that can trigger it? Is it only resize?).
2. Separately, open the sources tab in your browser inspector and debug the javascript by setting breakpoints to validate if it is the resize detection logic in the Flowsheet-Cell component that is bouncing back and forth in a loop as described (you can search for fragments like `r.useEffect` or `_.checkTypeNumeric` in the compiled javascript file to find the right place), or if it might be something else. 

\
\
Initial thoughts are that it probably has to do with as you described, the clinical-result has the built-in size detector for when the result has the "isNumeric" type, and when the full inner clinical-result value does not fit within the available space, it swaps the internal display for the numericOverflowDisplay text. For reference, that logic is here: 
https://github.com/cerner/terra-clinical/blob/8ced47320e0d673233e5ae06685c23ce97c04d77/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L334-L339

The flowsheet-cell component was not tested with any other sibling elements (like the check-box you have added), sharing the same space of a bounding parent container, and so it could be causing an infinite resize-checking loop perhaps, but will need to be confirmed that is the cause of the flicker, and therefore also the unresponsiveness. 

\
\
As you mentioned in your possible solution, the `overflow:hidden` was removed from the`  .flowsheet-result-cell` container with [PR#633](https://github.com/cerner/terra-clinical/pull/633/files#diff-a1ddcf8aab83b32b77a0d70d2a89972efb06e0bbe548f6cfd442b86ed5e8dc06L9), and although we didn't include comments as to why it was removed, I do remember it was intentionally done - so I would not immediately move to make that the immediate fix from Terra. It can be revisited as an option, but after additional style investigation. It could be the styles being applied to the checkbox element, or the composition of the two together within the parent container that should be looked at further. Posting links to your project on our internal communication boards would allow someone to help look at it further.

**Comment by JananiGunasekaran** [comment]
1. This issue happens on 2 scenarios:
i) When there is a checkbox and a numeric result (eg: 362.4343) that overflows the cell.
ii) Resize + When there is a checkbox and a numeric result (eg: 362.4343) that overflows the cell.

Attached videos for both scenarios. 


https://user-images.githubusercontent.com/60426528/105483928-93f21180-5cd0-11eb-8e6e-387ea8321130.mp4



https://user-images.githubusercontent.com/60426528/105483840-7329bc00-5cd0-11eb-9cf1-734b6882637d.mp4






Note: The video with resize issue was taken few days back when i was trying out few things to see what could resolve this issue. Please ignore the overflow fix i had tried on the video.

2. I put breakpoints in the code on these lines (r.useEffect or _.checkTypeNumeric) and it keeps hitting them back and forth in a loop when this issue occurs.

This is the link to my branch where i have results such that this issue can be reproduced : https://github.cerner.com/Assessments/device-value-flowsheet-js/tree/test

The issue can be reproduced without resize itself on the tests tab. The issue with resize can be reproduced on choosing the components tab and resizing the browser window size like shown in the video.

**Comment by JananiGunasekaran** [comment]
@neilpfeiffer Can you please provide an update on this?

**Comment by neilpfeiffer** [comment]
Thanks @JananiGunasekaran, after investigation we were able to replicate the issue you described, occurring at the particular critical widths in the 1-2px range when the `isNumeric` type result in the Flowsheet cell. We found that this issue occurred any time another sibling element with dimension is placed in the same parent container as the flowsheet-result-cell component, and we have two items for resolution.

As @BenBoersma mentioned in his spike, from a pure construction standpoint, this situation was not part our original design intent for the flowsheet-result-cell, it was intended to be the only item within it's parent container, always occupying the full space of a grid-cell and not competing for remaining space with siblings around it. Long term, we should plan to figure out a better path forward for a checkbox-toggle-selectable type flowsheet cell, to ensure the best accessibility and interaction patterns, which I will highlight your current challenges at the end.


For resolutions to this particular flickering and size detection re-render issue, we prototyped changes that will resolve the problem, and we suggest two items, one change will need to be done on your side, and a second will be a change Terra will make:
1. **Assessments / Device-Value-Flowsheet change**: 
Since the original design intent of the flowsheet-result-cell is to be the full width of the available parent cell, we suggest that the most stable way to use this component is to add additional styling that keeps it being implemented in a way that treats it that way, even though the checkbox element is an added sibling. 
    1. Either (a) introduce a new parent wrapper div to hold both the checkbox-wrapper (and current children) and the flowsheet-result-cell that has these styles: `padding-left: 1.92857rem; position: relative; width: 100%;`, or (b) add these styles to the current GridCell result container parent div _(has the complied class `GridCell-module__result-container___2ir0j`) _conditionally when you are adding a checkbox in that cell. This change will add padding on the left to remove available cell space for the flowsheet-result-cell while allowing the flowsheet-result-cell to continue to assume it has 100% width of it's parent.
    2. Add to your current checkbox-wrapper div _(has the complied class `GridCellCheckbox-module__checkbox-wrapper___VXk_j`)_ these styles: `left: 0; position: absolute;`. This will take the checkbox out of the document flow, which allows the flowsheet-result-cell to think it has full width of it's parent. _(The key to making this work is that any element with absolute positioning needs for its parent to explicitly set relative position to keep it bound to its expected position.)_

2. **Terra change**:
The changes listed above alone will resolve the flicker for your project, but may not prevent it from happening in other places if also used in similar ways, so Terra would like to put in a back-up protection for the time being while this component continues to mature and be enhanced. As you mentioned in the `Possible Solution` for the issue description, providing "overflow: hidden" does partially resolve the flicker issue and better helps for the truncation being applied in the flowsheet-result-cell. We originally removed it incase a grid cell was too small (mainly height) and was clipping the icons/multiple-results stack indicators, so we wanted them to overflow as indication the consuming grid should adjust their row height without loosing visual fidelity if the dimensions were close. So Terra is adding this PR https://github.com/cerner/terra-clinical/pull/744 which adds back `overflow: hidden-x;` as the failsafe protection. 

Hopefully, doing both of these items should completely resolve your visual flicker.
\
\
\
On a separate note, I would recommending scheduling some time to do a review of your current construction for accessibility, both keyboard-user interactions and for screenreader interactions. Your current markup structure sets the role of button to one of your main parent containers inside each result cell, but then you introduce the input type=checkbox as a deeply nested child of the div which is acting like a button. This puts keyboard interaction and screenreaders in not a good spot to properly work together. What you should be looking for is the checkbox toggle to be a sibling of the button, such that you can either select the result (check the checkbox) or select the "view more details" of a given result independently. This warrants us taking time to partner and come up with an appropriate best solution between Terra and consuming applications.

**Comment by JananiGunasekaran** [comment]
Thanks @neilpfeiffer. We will incorporate the mentioned change from our end.
