### ISSUE TITLE
[spike] Investigate the "View Results message flashing in a cell causes application to become unresponsive." issue in terra-clinical

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-clinical#741]
# Story

## Description

As a terra developer I need to figure out what is happening in the clinical results cell with respect to https://github.com/cerner/terra-clinical/issues/738

## Motivation

So that our consumers have feedback on whether this is an issue with their implementation or with the code itself

## Definition of Done

We'll know we're done when we either have feedback to the team on how to fix their issue, or have details logged on https://github.com/cerner/terra-clinical/issues/738 with specifics on the problem

**Comment by JananiGunasekaran** [comment]
@BenBoersma Can you please let us know by when we can expect this fix?

**Comment by JananiGunasekaran** [comment]
@BenBoersma Can you please provide an update on this?

**Comment by BenBoersma** [comment]
Spiking into this we were successfully able to recreate the issue locally, however recreating it locally required us to implement FlowsheetResultCell in a very specific way that it was not designed for. This is due to styles being applied outside of the clinical result that will need to be adjusted. @neilpfeiffer should be providing a more in depth answer on the [main issue.](https://github.com/cerner/terra-clinical/issues/738)

**Comment by JananiGunasekaran** [comment]
@BenBoersma Thank you for the update.
