### ISSUE TITLE
Action header missing translation, message fallback

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#99]
# Issue Description
When action header was missing the en translation, the component still loaded correctly. This was the error I saw in the console:

![image](https://user-images.githubusercontent.com/8146159/27405455-36913f5e-5697-11e7-9b67-065cab1bb92b.png)

This is what the component looked like:
![image](https://user-images.githubusercontent.com/8146159/27405457-3b6226c4-5697-11e7-8a59-614c5f4b8d6c.png)

When translations are missing, it should not use the message id as a fallback

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
Looked into `intl.formatMessage`. It will use id as fallback if a default message is not provided. We will want to explore what the best approach will be if a translation is missed/not provided.

**Comment by windse7en** [comment]
This is the default behavior from `intl.formatMessage`. If there are no translations for specified id, it will try to show default message at first. If there is also no default message, it will show translation id and throw console errors. 

I believed the initial reason to show translations id and throw console errors, is to give developers alerts on translation missing and they will be responsible for providing translations. And we don't have the fallback locale for default messages.

Consumers can define their strategy for the translation fallback, like providing the default messages instead of the translation id. In that case, we may want to provide a script to check if there are missing translations.

**Comment by bjankord** [comment]
Consensus is to keep error messages if translations are missing.
